-- authority
INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ROLE_MOD');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'ROLE_USER');

-- user
INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (1, 'user_mod1', /*vp_mod1*/'{bcrypt}$2y$06$5IgfvcRCT3IqbzJTjAv.OulBDsHKqQUVf7AW8gYODKoPKXqOBLvpW', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (2, 'user_mod2', /*vp_mod2*/'{bcrypt}$2y$06$3oiACFMlhGa4AfaDQdPcoOm5dqft12LqN2/tclpS5ckeKvO4tX/tO', FALSE, FALSE, FALSE, TRUE);

-- user to authority
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 2);